### ISSUE TITLE
hyperf2.0安装失败

### ISSUE THREAD

**Issue by cruelwolfking** [lphkxd/hyperf-jwt#2]
Problem 1
    - Can only install one of: hyperf/framework[v2.0.0, 1.1.x-dev].
    - Can only install one of: hyperf/framework[1.1.x-dev, v2.0.0].
    - Can only install one of: hyperf/framework[1.1.x-dev, v2.0.0].
    - mzh/hyperf-jwt v0.1.4 requires hyperf/framework ~1.1.0 -> satisfiable by hyperf/framework[1.1.x-dev].
    - Installation request for mzh/hyperf-jwt ^0.1.4 -> satisfiable by mzh/hyperf-jwt[v0.1.4].
    - Installation request for hyperf/framework (locked at v2.0.0, required as ~2.0.0) -> satisfiable by hyperf/framework[v2.0.0].

**Comment by lphkxd** [comment]
已更新至2.0
